<h1>Awave monitor</h1>
<?php $settings = awavemonitor_get_settings() ?>
<?php $token = defined("MONITORING_TOKEN") ? MONITORING_TOKEN : ""; ?>

<?php if (!empty($token)): ?>

    <h2><?= $token ?></h2>
    <pre><?php print_r($settings); ?></pre>

    <a target="_blank" href="?token=<?= $token ?>&monitoring=1">Test output</a>

<?php else : ?>
    <?php if (awavemonitor_ignore_domain()): ?>
        <h2>No token</h2>
        <p> Looks like domain is in ignore list, no autogenerated token for token for you.<br/>
            If you want to have it you can add it manually as constant (MONITORING_TOKEN) in wp-config.php</p>
        <h2>Ignored domains that contains: </h2>
        <p>
            <?= implode("<br/>",awavemonitor_domain_ingore_list()); ?>
        </p>
    <?php endif; ?>
<?php endif; ?>
